language: bash
services: docker

env:
  - VERSION=1.6 VARIANT=
  - VERSION=1.6 VARIANT=alpine
  - VERSION=1.5 VARIANT=
  - VERSION=1.5 VARIANT=alpine
  - VERSION=1.4 VARIANT=
  - VERSION=1.4 VARIANT=alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="haproxy:${VERSION}${VARIANT+-$VARIANT}"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
